모든 출처: 이스트소프트 백엔드 개발자 오르미 5기

# 에러 vs 예외

- **에러 Error**: 프로그램 실행 중 발생하는 심각한 문제로, 시스템 레벨에서 발생하며 프로그래머가 직접 처리할 수 없고 프로그램의 비정상적인 종료를 야기함
  - ex ) `OutOfMemoryError`, `StackOverflowError`  등
- **예외 Exception**: 프로그램 실행 중 발생하는 비정상적인 상황으로, 프로그래머가 적절히 처리하여 비정상적인 종료를 방지할 수 있음
  - `RuntimeException`: 언체크드 예외(Unchecked Exception) → 컴파일 시점에서 **예외 처리 강제** ❌, **프로그래밍 오류**에 의해 발생
    - `NullPointerException`, `ArrayIndexOutOfBoundsException` 등
  - `IOException`, `SQLException` 등: 체크드 예외(Checked Exception) → 컴파일 시점에서 **예외 처리 강제**(`try-catch / throws` 사용), **외부 요인**에 의해 발생
    - `FileNotFoundException`, `IOException` 등

    <aside>
    💡 에러와 예외처리를 위한 클래스들의 **상속** 형태

  최상위 조상 클래스      `Throwable`
  /          \
  조상 클래스              `Error`   `Exception`
  /           \    
  부모 클래스    `RuntimeException`    `IOException, SQLException` 등
  언체크드 예외                        체크드 예외
  |                                                 |
  자식 클래스   `NullPointerException` 등  `FileNotFoundExceptio` 등

    </aside>


# 예외 처리

- Java 에 정의되어 있는 예외 클래스들을 이용하여 예외 처리
- 메서드 내부에서는 `throw` , `new` 키워드 필요
- 메서드 레벨에서는 `throws` 키워드 사용, `new` 는 필요없음
- 일반적인 예외 처리 방법
  - `try-catch` 블록 사용

    ```java
    // try-catch 블록 사용
    public class TryCatchExample {
      public static void main(String[] args) {
          try {
              int result = 10 / 0; // ArithmeticException 발생
              System.out.println(result);
          } catch (ArithmeticException e) {
              System.out.println("0으로 나눌 수 없습니다.");
          }
          System.out.println("정상적으로 종료되었습니다.");
      }
    }
    ```

  - `throws` 키워드 사용: `throws` 키워드가 있는 메서드를 호출한 쪽으로 예외를 전파한 후 `try-catch` 문으로 예외를 처리

    ```java
    	// try-catch 블록 사용 + throws 키워드 사용
    public class ThrowsExample {
      public static void main(String[] args) {
          try {
              divide(10, 0);
          } catch (ArithmeticException e) {
              System.out.println("0으로 나눌 수 없습니다.");
          }
      }
    
      public static int divide(int a, int b) throws ArithmeticException {
          return a / b;
      }
    }
    ```

- 예외 처리 후에는 `finally`  블록을 이용하여 예외 발생 여부 관계없이 행동을 수행시킬 수 있음 (필수는 아니며 주로 자원 해제를 위해 사용)

    ```java
    try {
        int result = 10 / 0;
        System.out.println(result);
    } catch (ArithmeticException e) {
        System.out.println("0으로 나눌 수 없습니다.");
    } finally {
        System.out.println("Finally 블록은 항상 실행됩니다.");
    }
    ```

- `Exception` 클래스를 상속받아 직접 exception을 커스텀 할 수 있음

```java
public class BankAccount {
    private int balance;

    public void withdraw(int amount) throws InsufficientBalanceException {
        if (balance < amount) {
            throw new InsufficientBalanceException("잔액이 부족합니다.");
        }
        balance -= amount;
    }
}

**public class InsufficientBalanceException extends Exception {
    public InsufficientBalanceException(String message) {
        super(message);
    }
}**

public class BankApplication {
    public static void main(String[] args) {
        BankAccount account = new BankAccount();
        try {
            account.withdraw(10000); // InsufficientBalanceException 발생
        } catch (InsufficientBalanceException e) {
            System.out.println(e.getMessage());
        }
    }
}
```